config/routes.rb
Rails.application.routes.draw do
  get 'posts/new'
  post 'posts/create', as: :posts
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "site#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    if @post.valid?
      @post.save
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def post_params
    params.require(:post).permit(:body)
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Instaclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="nav">
      <%= turbo_frame_tag "post-form" do %>
        <%= link_to 'New post', posts_new_path %>
      <% end %>
      <% if user_signed_in? %>
        <%= link_to 'Sign out', destroy_user_session_path, data: {turbo_method: :delete}%>
      <% else %>
        <%= link_to 'Sign in', new_user_session_path %>
      <% end %>
    </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-author">
    <div class="avatar avatar-<%= rand(1..27) %>"></div>
    <div><%= post.user.email %></div>
  </div>
  <div class="post-body">
    <span><%= post.body %></span>
  </div>
  <div class="post-actions">
    <div class="post-actions-like"></div>
    <div class="post-actions-comments">4 comments</div>
  </div>
  <div class="post-comments">
    <div class="comment">
      <span class="comment-author">
        Joe
      </span>
      This is something I said
    </div>
    <div class="comment">
      <span class="comment-author">
        Joe
      </span>
      This is something I said
    </div>
  </div>
</div>

app/views/posts/create.turbo_stream.erb
<%= turbo_stream.prepend "posts" do %>
  <%= render partial: "post", locals: {post: @post} %>
<% end %>

app/views/posts/new.html.erb
<%= turbo_frame_tag "post-form" do %>
  <%= form_with model: @post do |f| %>
    <div class="field">
      <%= f.text_field :body %>
      <%= f.submit :Send %>
    </div>
  <% end %>
<% end %>

app/views/site/index.html.erb
Welcome
<div id="posts"></div>